"""Rendered configs stay byte-identical to what the released main branch produced.

tests/fixtures/golden_main.json holds the output of cases() below, generated by
running this same file against the code of main at the commit recorded in the
fixture (v0.3.3). Every option added since then is off by default, so today's
code must still produce exactly those bytes. Regenerate only on purpose, and
only from main (see "how" in the fixture), never from a working branch.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from xrayui.core import render, routing, settings
from xrayui.core.profiles import Profile

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "golden_main.json"
TEMPLATE = Path(__file__).resolve().parent.parent / "config.template.json"

_TLS = {"address": "a.example", "port": 443, "id": "11111111-1111-1111-1111-111111111111",
        "security": "tls", "sni": "a.example"}


def _profiles() -> dict[str, Profile]:
    return {
        "vless-reality": Profile(protocol="vless", address="a.example", port=443,
                                 id="11111111-1111-1111-1111-111111111111", network="tcp",
                                 security="reality", sni="www.example.com", fp="chrome",
                                 pbk="Z84J2IelR9ch3k8VtlVhhs5ycBUlXA7wHBWcBrjqnAw", sid="ab",
                                 flow="xtls-rprx-vision"),
        "vless-ws": Profile(protocol="vless", network="ws", path="/ws", host="h.example", **_TLS),
        "vless-xhttp": Profile(protocol="vless", network="xhttp", path="/x", xhttp_mode="auto",
                               xhttp_extra='{"xmux": {"maxConcurrency": "16-32"}}', **_TLS),
        "vless-grpc": Profile(protocol="vless", network="grpc", service_name="svc", **_TLS),
        "vless-httpupgrade": Profile(protocol="vless", network="httpupgrade", path="/hu",
                                     host="h.example", **_TLS),
        "vmess-tcp-http": Profile(protocol="vmess", address="a.example", port=80,
                                  id="11111111-1111-1111-1111-111111111111", network="tcp",
                                  header_type="http", path="/", host="h.example"),
        "trojan-tls": Profile(protocol="trojan", **_TLS),
        "shadowsocks": Profile(protocol="shadowsocks", address="a.example", port=8388,
                               id="secret", ss_method="aes-128-gcm"),
        "hysteria2": Profile(protocol="hysteria2", address="a.example", port=443, id="auth",
                             sni="a.example", hy2_obfs_password="obfs", hy2_ports="20000-30000",
                             hy2_up_mbps=10, hy2_down_mbps=50),
        "wireguard": Profile(protocol="wireguard", address="a.example", port=51820,
                             id="aB/c+d1EF/GHI=", pbk="pQ+R/ST8uVW=", wg_reserved="1,2,3",
                             wg_local_address="10.0.0.2/32", wg_keepalive=25),
        "vless-ip-tls": Profile(protocol="vless", address="203.0.113.7", port=443,
                                id="11111111-1111-1111-1111-111111111111", network="tcp",
                                security="tls", sni="a.example"),
    }


def _variants() -> dict[str, dict]:
    base_routing = copy.deepcopy(settings.DEFAULTS["routing"])
    base_dns = copy.deepcopy(settings.DEFAULTS["dns"])
    base_core = copy.deepcopy(settings.DEFAULTS["core"])

    frag_mux = copy.deepcopy(base_core)
    frag_mux["fragment"]["enabled"] = True
    frag_mux["mux"]["enabled"] = True

    split_dns = copy.deepcopy(base_dns)
    split_dns.update(domestic_servers=["178.22.122.100"], remote_via_tunnel=True,
                     parallel_query=True)

    return {
        "defaults": {"routing": base_routing, "dns": base_dns, "core": base_core,
                     "stats": True, "include_tun": True},
        "fragment-mux": {"routing": base_routing, "dns": base_dns, "core": frag_mux,
                         "stats": True, "include_tun": True},
        "split-dns": {"routing": base_routing, "dns": split_dns, "core": base_core,
                      "stats": True, "include_tun": True},
        "no-tun": {"routing": base_routing, "dns": base_dns, "core": base_core,
                   "stats": False, "include_tun": False},
    }


def cases() -> dict[str, str]:
    out: dict[str, str] = {}
    for pname, profile in _profiles().items():
        for vname, v in _variants().items():
            out[f"{pname}/{vname}"] = render.build_text(
                profile=profile, iface_alias="eth0", template_path=TEMPLATE,
                routing_rules=routing.build_rules(v["routing"]),
                domain_strategy=routing.domain_strategy_for(v["routing"]),
                stats=v["stats"], include_tun=v["include_tun"], log_level="warning",
                dns_cfg=v["dns"], tun_mtu=1420, server_ip="203.0.113.7", core_cfg=v["core"])
    return out


@pytest.fixture(scope="module")
def golden() -> dict[str, str]:
    return json.loads(FIXTURE.read_text(encoding="utf-8"))["configs"]


@pytest.fixture(scope="module")
def rendered() -> dict[str, str]:
    return cases()


def test_the_case_list_matches_the_fixture(golden, rendered):
    assert sorted(rendered) == sorted(golden)


@pytest.mark.parametrize("name", sorted(cases()))
def test_config_is_byte_identical_to_main(name, golden, rendered):
    assert rendered[name] == golden[name], f"{name} differs from main's output"
