"""Regression check for the render._apply_profile -> core/outbounds split.

tests/fixtures/render_baseline.json was generated by running main's
(pre-split) render.py against this same profile set, before the split. If
this test still passes, the split changed no rendered bytes.
"""
import json
from pathlib import Path

from xrayui.core import render
from xrayui.core.profiles import Profile

TEMPLATE = Path(__file__).resolve().parent.parent / "config.template.json"
BASELINE = json.loads(
    (Path(__file__).resolve().parent / "fixtures" / "render_baseline.json").read_text(encoding="utf-8")
)

PROFILES = {
    "vless_tcp_none": Profile(
        name="p1", protocol="vless", address="1.2.3.4", port=443, id="uid-1",
        encryption="none", network="tcp", security="none",
    ),
    "vless_tcp_tls": Profile(
        name="p2", protocol="vless", address="a.example.com", port=443, id="uid-2",
        encryption="none", flow="xtls-rprx-vision", network="tcp", security="tls",
        sni="a.example.com", fp="chrome", alpn="h2,http/1.1",
    ),
    "vless_ws_tls": Profile(
        name="p3", protocol="vless", address="b.example.com", port=8443, id="uid-3",
        network="ws", security="tls", sni="b.example.com", fp="firefox",
        path="/ws-path", host="b.example.com",
    ),
    "vless_grpc_tls": Profile(
        name="p4", protocol="vless", address="c.example.com", port=443, id="uid-4",
        network="grpc", security="tls", sni="c.example.com", service_name="grpc-svc",
    ),
    "vless_h2_tls": Profile(
        name="p5", protocol="vless", address="d.example.com", port=443, id="uid-5",
        network="h2", security="tls", sni="d.example.com",
        path="/h2-path", host="d1.example.com,d2.example.com",
    ),
    "vless_ws_reality": Profile(
        name="p6", protocol="vless", address="203.0.113.5", port=443, id="uid-6",
        network="ws", security="reality", sni="www.microsoft.com", fp="chrome",
        pbk="PUBKEY", sid="ab12", spx="/spider", path="/rws", host="www.microsoft.com",
    ),
    "wireguard_ipv4": Profile(
        name="wg1", protocol="wireguard", address="1.2.3.4", port=51820,
        id="SECRETKEY", pbk="PEERKEY", wg_local_address="10.0.0.2/32, fd00::2/128",
        wg_preshared="PSK", wg_reserved="1,2,3", wg_mtu=1280, wg_keepalive=25,
    ),
    "wireguard_ipv6_endpoint": Profile(
        name="wg2", protocol="wireguard", address="2606:4700:d0::a29f:c001",
        port=2408, id="S", pbk="P",
    ),
}


def test_baseline_covers_every_profile():
    assert set(BASELINE) == set(PROFILES)


def test_outbounds_split_reproduces_main_byte_for_byte():
    for key, profile in PROFILES.items():
        out = json.loads(render.build_text(profile, "Wi-Fi", TEMPLATE))
        assert out == BASELINE[key], f"render output changed for {key}"
