"""Linux backend: elevation, DNS under systemd-resolved, and coexisting clients.

Each case here was a way the Linux build failed while Windows worked: the
elevated window never opened, lookups blackholed, a disconnect left no DNS, and
connecting killed another client's xray.
"""
from __future__ import annotations

import re
import sys
import types

import pytest

from xrayui import elevate, paths
from xrayui.core import _net_posix as posix
from xrayui.core import connection, xray
from xrayui.core.network import DnsState, Interface
from xrayui.core.state import State

LINUX_ONLY = pytest.mark.skipif(sys.platform != "linux", reason="Linux network backend")


def _record(monkeypatch, stdout=""):
    ran: list[list[str]] = []

    def fake_run(args, **_k):
        ran.append(list(args))
        return types.SimpleNamespace(returncode=0, stdout=stdout(args) if callable(stdout) else stdout)

    monkeypatch.setattr(posix.proc, "run", fake_run)
    return ran


# -- elevation -------------------------------------------------------------
def _relaunch(monkeypatch, rc):
    calls = []
    monkeypatch.setattr(elevate.shutil, "which",
                        lambda name: f"/usr/bin/{name}" if name in ("pkexec", "env") else None)
    monkeypatch.setattr(elevate.subprocess, "call", lambda args: calls.append(args) or rc)
    monkeypatch.setenv("DISPLAY", ":0")
    monkeypatch.setenv("WAYLAND_DISPLAY", "wayland-0")
    monkeypatch.setenv("XAUTHORITY", "/run/user/1000/xauth")
    return calls, elevate._relaunch_linux()


def test_pkexec_relaunch_carries_the_display_into_the_elevated_process(monkeypatch):
    calls, started = _relaunch(monkeypatch, 0)
    assert started
    args = calls[0]
    assert args[:2] == ["/usr/bin/pkexec", "/usr/bin/env"]
    assert "DISPLAY=:0" in args
    assert "WAYLAND_DISPLAY=wayland-0" in args
    assert "XAUTHORITY=/run/user/1000/xauth" in args
    # A source run must still find the package from root's home directory.
    assert any(a.startswith("PYTHONPATH=") for a in args)


@pytest.mark.parametrize("rc", [126, 127])
def test_refused_pkexec_falls_back_to_an_unelevated_window(monkeypatch, rc):
    _calls, started = _relaunch(monkeypatch, rc)
    assert started is False


# -- DNS under systemd-resolved -------------------------------------------
@LINUX_ONLY
def test_resolved_dns_is_claimed_on_the_tunnel_not_the_physical_link(monkeypatch):
    monkeypatch.setattr(posix, "_resolved_active", lambda: True)
    ran = _record(monkeypatch)

    posix.set_dns_loopback("enx0")

    # resolved pins a link's queries to it; 127.0.0.1 is unreachable via a NIC.
    assert not any("enx0" in cmd for cmd in ran)
    assert not any("127.0.0.1" in cmd for cmd in ran)
    assert ["resolvectl", "dns", posix.TUN_NAME, posix.TUN_DNS] in ran
    assert ["resolvectl", "domain", posix.TUN_NAME, "~."] in ran


def test_tunnel_dns_address_routes_into_the_tun():
    import ipaddress
    net = ipaddress.ip_network(f"{posix.TUN_ADDRESS}/{posix.TUN_PREFIX_LEN}", strict=False)
    assert ipaddress.ip_address(posix.TUN_DNS) in net
    assert posix.TUN_DNS != posix.TUN_ADDRESS


@LINUX_ONLY
def test_restore_leaves_the_physical_links_dns_alone(monkeypatch):
    monkeypatch.setattr(posix, "_resolved_active", lambda: True)
    ran = _record(monkeypatch, stdout="Link 8 (enx0): 4.2.2.1 8.8.8.8\n")

    assert posix.restore_dns("enx0", DnsState(mode="RESOLVED")) is True
    # revert would wipe what NetworkManager pushed: no DNS until reconnect.
    assert ["resolvectl", "revert", "enx0"] not in ran
    assert ["resolvectl", "revert", posix.TUN_NAME] in ran


@LINUX_ONLY
def test_restore_still_rescues_a_link_an_older_build_pinned_to_loopback(monkeypatch):
    monkeypatch.setattr(posix, "_resolved_active", lambda: True)
    ran = _record(monkeypatch, stdout="Link 8 (enx0): 127.0.0.1\n")

    posix.restore_dns("enx0", DnsState(mode="RESOLVED"))
    assert ["resolvectl", "revert", "enx0"] in ran


def test_resolv_conf_backup_survives_the_state_round_trip(monkeypatch, tmp_path):
    monkeypatch.setattr(paths, "state_dir", lambda: tmp_path)
    original = ["# Generated by NetworkManager", "search lan", "nameserver 192.168.1.1"]
    State().save(Interface("eth0", "192.168.1.5", "192.168.1.1"), "1.2.3.4", 5,
                 DnsState(mode="FILE", servers=original))

    assert State().dns_state().servers == original


def test_dns_server_list_still_parses_one_per_line(monkeypatch, tmp_path):
    monkeypatch.setattr(paths, "state_dir", lambda: tmp_path)
    State().save(Interface("Wi-Fi", "10.0.0.2", "10.0.0.1"), "1.2.3.4", 5,
                 DnsState(mode="STATIC", servers=["1.1.1.1", "8.8.8.8"]))
    assert State().dns_state().servers == ["1.1.1.1", "8.8.8.8"]


# -- other VPN clients -----------------------------------------------------
def test_only_our_own_xray_is_matched(monkeypatch, tmp_path):
    cfg = tmp_path / "sush.Tun" / "config.runtime.json"
    monkeypatch.setattr(paths, "runtime_config", lambda: cfg)
    pattern = re.compile(xray._own_pattern())

    assert pattern.search(f"/tmp/_MEI123/xray run -c {cfg}")
    assert not pattern.search("/home/u/.local/share/v2rayN/bin/xray/xray run -c config.json")
    # The dot in the path is literal, not "any character".
    assert not pattern.search(f"xray run -c {str(cfg).replace('sush.Tun', 'sushXTun')}")


@LINUX_ONLY
def test_foreign_tunnel_names_the_device_another_vpn_steers_through(monkeypatch):
    _record(monkeypatch, stdout='[{"dst":"1.1.1.1","dev":"singbox_tun"}]')
    assert posix.foreign_tunnel("enx0") == "singbox_tun"

    _record(monkeypatch, stdout='[{"dst":"1.1.1.1","gateway":"172.21.1.1","dev":"enx0"}]')
    assert posix.foreign_tunnel("enx0") is None

    _record(monkeypatch, stdout="")  # offline: `ip route get` prints nothing
    assert posix.foreign_tunnel("enx0") is None


def test_connect_refuses_while_another_vpn_owns_the_route(monkeypatch):
    monkeypatch.setattr(connection.network, "detect_interface",
                        lambda: Interface("enx0", "172.21.1.24", "172.21.1.1"))
    monkeypatch.setattr(connection.network, "foreign_tunnel", lambda alias: "singbox_tun")
    conn = connection.Connection()
    monkeypatch.setattr(conn.state, "is_connected", lambda: False)
    profile = types.SimpleNamespace(address="1.2.3.4", id="u", protocol="vless", pbk="")

    with pytest.raises(connection.ConnectError, match="singbox_tun"):
        conn.connect(profile)
